---
roles:
  - name: robertdebock.epel
  - name: jq
    src: https://github.com/ansible-roles-matsumura/jq.git
  - name: terraform
    src: https://github.com/ansible-roles-matsumura/terraform.git

collections:
  - name: community.general
