---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether Terraform is installed
      ansible.builtin.command: terraform -version
      register: TERRAFORM_INSTALLED
      changed_when: False
      ignore_errors: True

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Make sure Terrafrom is installed
      ansible.builtin.debug:
        var: TERRAFORM_INSTALLED

    - name: Show OS version
      ansible.builtin.debug:
        var: OS_VERSION
